name: Suitable Conditions
favicon: null
layout_spectrum: 0.3704129629768431
typography_spectrum: 0.6950559036340564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8085852453950793
  lightness: 0.348558709025383
  saturation: 0.3987170858308673
  rhythmicContrast: 0.7644613550510257
purpose: []
